# Generated by Django 4.1.4 on 2022-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "registration_number_primary_key",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("model", models.CharField(max_length=30)),
                ("company", models.CharField(max_length=20)),
                ("price", models.IntegerField(max_length=20)),
                ("year_of_manufacture", models.IntegerField()),
                ("cc", models.IntegerField()),
            ],
        ),
    ]
